## README: If you want to use the example data from the package, you run 0--.->A->B->Y->C->D->E. 
## README: If you want to see how your input data works here,    you run 0->X--.->B->Y--.->D
#-----------------------------
# 0. Setup environment & load dataset
getwd();
workingDir = "/Users/jylee43/Google\ Drive/coursework_2017SPRING/ProblemSolving/2_MI_minet_JL/";
setwd(workingDir); 
getwd();
#-----------------------------
# X. load dataset
ExprData  <- read.table("Randome_Example_Input.csv", sep = "," , header = T, na.strings ="", stringsAsFactors= F)
#dim(ExprData)
syn.data = ExprData[, 2: (dim(ExprData)[2]) ]
rownames(syn.data) = ExprData[,1]
syn.data=t(syn.data)
#dim(syn.data)
#head(syn.data)  
#-----------------------------
# A. syn.data Simulated Gene Expression Data
# Dataset containing 100 samples and 50 genes generated by the publicly available SynTReN generator using a yeast source network 
library(minet)

data(syn.data)
class(syn.data)
dim(syn.data) 
head(syn.data)
#boxplot(t(syn.data))
#summary(syn.data)
#heatmap(as.matrix(syn.data))

#-----------------------------
# B. Mutual Information Network. 
# For a given dataset, minet infers the network in two steps. First, the mutual information between all pairs of variables in dataset is computed according to the estimator argument. Then the algorithm given by method considers the estimated mutual informations in order to build the network. 
library(minet)

clr.net <- minet( syn.data, method="clr", estimator="spearman" )
head(clr.net)
arc.net <- minet( syn.data, method="aracne", estimator="spearman" )
head(arc.net)
mrn.net <- minet( syn.data, method="mrnet", estimator="spearman" )  
head(mrn.net)
mnb.net <- minet( syn.data, method="mrnetb", estimator="spearman" ) 
head(mnb.net)

#-----------------------------
# Y. Write network matrix to CSV
write.csv(clr.net, file = "minet_clr_net.csv",row.names=T)
write.csv(arc.net, file = "minet_arc_net.csv",row.names=T)
write.csv(mrn.net, file = "minet_mrn_net.csv",row.names=T)
write.csv(mnb.net, file = "minet_mnb_net.csv",row.names=T)

#-----------------------------
# C. validate: Inference Validation
# validate compares the infered network to the true underlying network for several threshold values and appends the resulting confusion matrices to the returned object.
# syn.net: SynTReN Source Network is the true underlying network used to generate the dataset loaded by data(syn.data) - see syn.data.

data(syn.net)  
clr.tbl <- validate( clr.net, syn.net ) 
head(clr.tbl)
arc.tbl <- validate( arc.net, syn.net ) 
head(arc.tbl)
mrn.tbl <- validate( mrn.net, syn.net ) 
head(mrn.tbl)
mnb.tbl <- validate( mnb.net, syn.net ) 
head(mnb.tbl)

max(fscores(validate( clr.net, syn.net )))
max(fscores(validate( arc.net, syn.net )))
max(fscores(validate( mrn.net, syn.net )))
max(fscores(validate( mnb.net, syn.net )))
#-----------------------------
# D. visualization
library(Rgraphviz)
#graph <- as(clr.net, "graphNEL")
graph <- as(arc.net, "graphNEL")
#graph <- as(mrn.net, "graphNEL")
#graph <- as(mnb.net, "graphNEL")
plot(graph,nodeAttrs=makeNodeAttrs(graph, fontsize=50))

#-----------------------------
# E. Plot PR-Curves max(fscores(mr.tbl)) 
dev <- show.pr(clr.tbl, col="red",type="b") 
dev <- show.pr(arc.tbl, device=dev, col="blue", type="b") 
dev <- show.pr(mrn.tbl, device=dev, col="green", type="b") 
show.pr(mnb.tbl, device=dev, col="black",type="b") 
auc.pr(clr.tbl)
auc.pr(arc.tbl)
auc.pr(mrn.tbl)
auc.pr(mnb.tbl)
